name: master

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [linux-amd64, darwin-amd64]
        redskyctl: [1.3.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Install redskyctl and run test
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-add redskyctl $GITHUB_WORKSPACE
          asdf list-all redskyctl
          asdf plugin-test redskyctl $GITHUB_WORKSPACE 'redskyctl version' --asdf-tool-version ${{ matrix.redskyctl }}
